name: docs-release-action
description: Register new stable version of documentation

inputs:
  revision:
    required: true
  storage-bucket:
    required: true
  storage-access-key-id:
    required: true
  storage-secret-access-key:
    required: true
  version:
    default: ""
  update-only-version:
    required: false
    default: "false"
  server:
    default: "https://viewer.diplodoc.com"
  project-link:
    required: false
    description: "Link to the documentation project"

runs:
  using: composite
  steps:
    - name: Update version or head
      shell: bash
      run: |
        set -e

        ENDPOINT="head"
        if [[ "${{ inputs.update-only-version }}" == "true" ]]; then
          ENDPOINT="versions"
        fi

        RESPONSE_CODE=$(curl \
          --header "Content-Type: application/json" \
          --silent \
          --output RESPONSE \
          --write-out "%{http_code}" \
          --data-binary @- \
          ${{ inputs.server }}/_/api/$ENDPOINT <<< $(jq -c -n '{
                revision:"${{ inputs.revision }}",
                version:"${{ inputs.version }}",
                project:"${{ inputs.storage-bucket }}",
                accessKeyId:"${{ inputs.storage-access-key-id }}",
                secretAccessKey:"${{ inputs.storage-secret-access-key }}"
          }'))
        
        if [[ "$RESPONSE_CODE" == "200" ]]; then
          exit 0
        fi
        
        echo "::error::$(jq '.message' -r RESPONSE)"
        exit 1
        
    - name: Generate documentation link
      if: inputs.project-link != ''
      shell: bash
      run: |
        DOC_LINK="${{ inputs.project-link }}"
        echo "::notice title=Documentation Link::The production version of the documentation is available at: $DOC_LINK"
        echo "### Documentation Link" >> $GITHUB_STEP_SUMMARY
        echo "The production version of the documentation is available at: $DOC_LINK" >> $GITHUB_STEP_SUMMARY
