name: docs-release-action
description: Register new stable version of documentation

inputs:
  revision:
    required: true
  storage-bucket:
    required: true
  storage-access-key-id:
    required: true
  storage-secret-access-key:
    required: true
  version:
    default: ""
  server:
    default: "https://viewer.diplodoc.com"

runs:
  using: composite
  steps:
    - name: Update head
      shell: bash
      run: |
        curl \
          --header "Content-Type: application/json" \
          --data-binary @- \
          ${{ inputs.server }}/_/api/head <<EOF
        {
          "revision":"${{ inputs.revision }}",
          "version":"${{ inputs.version }}",
          "project":"${{ inputs.storage-bucket }}",
          "accessKeyId":"${{ inputs.storage-access-key-id }}",
          "secretAccessKey":"${{ inputs.storage-secret-access-key }}"
        }
        EOF
